[package]
name = "memory_model"
version = "0.1.0"
authors = ["The Chromium OS Authors"]

[dependencies]
libc = ">=0.2.39"
serde = { version = "^1.0.27", features = ["derive"] }
serde_derive = ">=1.0.27"

[dev-dependencies]
tempfile = ">=3.0.2"
